name: Documenter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        with:
          path: main_repo

      - name: Check out gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh_pages_repo

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'

      - name: Activate docs project
        run: julia --project=gh_pages_repo/docs -e 'using Pkg; Pkg.activate(); Pkg.instantiate()'

      - name: Develop package
        run: julia --project=gh_pages_repo/docs -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(), "main_repo"))); Pkg.instantiate()'

      - name: Generate and Deploy documentation
        run: julia --project=gh_pages_repo/docs --color=yes gh_pages_repo/docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
